

# --- CONFIGURATION ---
FORMAT = "int16"
CHANNELS = 1
RATE = 24000
AUDIO_CHUNK_SIZE = 8192 

# DSP Config
CROSSFADE_DURATION_SEC = 0.05
SAMPLES_PER_SEC = RATE * CHANNELS
CROSSFADE_SAMPLES = int(CROSSFADE_DURATION_SEC * SAMPLES_PER_SEC)

# Token Budget (100 WPM)
TOKEN_PER_WORD = 53
TOKEN_PER_TAG_SHORT = 150
TOKEN_PER_TAG_LONG = 400
BASE_TOKEN_OVERHEAD = 10

MAX_WORDS_PER_CHUNK = 15

# Buffering Config
BUFFER_DURATION_SEC = 6.0
BYTES_PER_SEC = RATE * 2 * CHANNELS
MIN_START_BYTES = BYTES_PER_SEC * BUFFER_DURATION_SEC 
REBUFFER_TARGET_SEC = 2.0
REBUFFER_TARGET_BYTES = BYTES_PER_SEC * REBUFFER_TARGET_SEC 

CONCURRENT_REQUESTS = 6
TTS_TIMEOUT = 60 * 3
QUEUE_MAX_SIZE = 2000

SERVER_URL = "https://maya1-tts-434000853810.europe-west1.run.app/v1/tts/generate"
DESCRIPTION_DEFAULT = "Realistic male voice in the 40s with British accent. Low pitch, mellow timbre, slow pacing."